development:
  host: localhost
  user: abchi
  password: 
  dbname: mtga_deckconverter
  port: 5432

production:
  host: <%= ENV['HOST_NAME'] %>
  user: <%= ENV['USER_NAME'] %>
  password: <%= ENV['PASSWORD'] %>
  dbname: <%= ENV['DATABASE_NAME'] %>
  port: <%= ENV['DATABASE_PORT'] %>
